//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.09 at 06:43:43 PM CST 
//


package autentica.cfdi.autentica;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the autentica.cfdi.autentica package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AutenticaResponseAutenticaResult_QNAME = new QName("http://cfdi.autentica/autentica", "AutenticaResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: autentica.cfdi.autentica
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AutenticaRequest }
     * 
     */
    public AutenticaRequest createAutenticaRequest() {
        return new AutenticaRequest();
    }

    /**
     * Create an instance of {@link AutenticaResponse }
     * 
     */
    public AutenticaResponse createAutenticaResponse() {
        return new AutenticaResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://cfdi.autentica/autentica", name = "AutenticaResult", scope = AutenticaResponse.class)
    public JAXBElement<String> createAutenticaResponseAutenticaResult(String value) {
        return new JAXBElement<String>(_AutenticaResponseAutenticaResult_QNAME, String.class, AutenticaResponse.class, value);
    }

}
