//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.09 at 06:43:43 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cfdi.autentica/autentica", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package autentica.cfdi.autentica;
